### ISSUE TITLE
Disguise removal is buggy

### ISSUE THREAD

**Issue by mathiascode** [tonibm19/DisguiseCraft#8]
When a player respawns after getting killed, and when a player rejoins the server, the player's visibility is set to true while still being disguised. The disguise mob only disappears when executing the /ud command or reloading the server.

The official DisguiseCraft plugin keeps the disguise when the player dies, but removes it when the player leaves the server.

**Comment by tonibm19** [comment]
It should nlt happen if a pmayer leaves and then rejoins the server.
See OnPlayerDestroyed hook in hooks.lua

**Comment by mathias-github** [comment]
I realised another plugin caused interference with the OnPlayerDestroyed hook.

My newest PR addresses the visibility issue after respawning.
